export const REQUESE_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';

export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_EXACT_ARTICLES = 'FETCH_EXACT_ARTICLES';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const CERTAIN_ARTILCE = 'CERTAIN_ARTICLE';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const GET_PRIVATE_ARTICLES = 'GET_PRIVATE_ARTICLES';

export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const TOGGLE_REGIST = 'TOGGLE_REGIST';

export const SHOW_EDITOR = 'SHOW_EDITOR';
export const HIDE_EDITOR = 'HIDE_EDOTOR';
